### ISSUE TITLE
책

### ISSUE THREAD

**Issue by miaekim** [benjioh5/icewall-guideline#13]
책 추천도 좋지않을까 :)?  물론 프로그래밍언어 책 말고 ㅎㅎ 
물론 이건 가이드라인이 아니긴 함 (..  부록에 들어갈정도)
the art of computer programming 이런거라던가..

해커와 화가
  -  YC  할배 폴 그레이엄의 개인 에세이
  -  어떻게 부자가 되는지(부제:  왜 인간들은 창업하나)
  -  해커들은 왜 새로은 프로그래밍 언어를 배우고자 하는지
  -  등등 똑똑한 해커들은 뭔 생각으로 살아가는지 이해하는데  도움을 줌

[SICP](https://mitpress.mit.edu/sicp/)
  -  이  책 읽으면 어디가서 컴덕소리 들음
  - 난 안읽음(실은 못읽겠음)
  - 최근 MIT도 이걸 커리큘럼엣 빼고 파이썬을 넣었다고 한다.

**Comment by benjioh5** [comment]
이슈가 쌓인다....
는 프로그래머 추천 도서 64선이나 50선 이런 리스트를 그냥 올려버릴까 아니면 내가 봤던 괜찮은 책들을 추천할까

솔직히 언어별 입문서 책 추천을 하고 싶기는 함. 입문서 이후 프레임워크나 더 배워야할 책들도 넣고 싶고...

**Comment by benjioh5** [comment]
이슈 클로징!

**Comment by miaekim** [comment]
그냥 잡설이긴 한데 왜 프로그래밍 언어를 책으로 배울까?  ..  공식 사이트 튜토리얼이 젤 좋을텐데!

물론 난 처음에 C배울 때 운성우 책으로 배웠었긴 함

**Comment by benjioh5** [comment]
@miaekim 일단 그 책을 보면 기본적으로 할 수 있는 걸 다 할 수 있기 떄문이 아닐까? 감을 잡는다고 해야하나?

**Comment by miaekim** [comment]
돌이켜보면 책보다 웹앱으로 인터렉티브 하게 배우는게 더 빨랐을거 같음 ...
