### ISSUE TITLE
레파지토리 설명이 너무 불친절합니다.

### ISSUE THREAD

**Issue by miaekim** [benjioh5/icewall-guideline#6]
> ICEWALL Univ. life guideline project 

지금 이따구로 쓰여있는데,

> [대학생존 가이드라인](https://www.gitbook.com/book/deadbeef/icewall-guideline/details) by ICEWALL 

이런식으로 깃북 링크를 붙이면 더 좋을거 같습니다. 그리고 어차피 한국어로 된 문서인데.. `Univ. life guideline project` 라니

**Comment by benjioh5** [comment]
네 알았습니다.
