### ISSUE TITLE
해외취업 문서는 만드실 의향있나요?

### ISSUE THREAD

**Issue by miaekim** [benjioh5/icewall-guideline#7]
만들면 거기에 기여할 의향은 있는데 'ㅅ'?
얼음벽 사람들은 그런거 관심 없을라나?

**Comment by benjioh5** [comment]
만들던지요.... 그냥 프로젝트 이름에서 ICEWALL을 제외시키는게 답 아닐까요 그러면.

**Comment by benjioh5** [comment]
사실, 여러 군데에서 사용하려고 만드는거라서 별 문제는 없을겁니다. 하셔도 됩니다.

**Comment by miaekim** [comment]
@benjioh5 여러군데에서 쓸거면 ICEWALL 특화부분은 따로 분리시키는 게 좋을 듯 합니다.

**Comment by benjioh5** [comment]
분화는 예정 중인데, 지금부터 하자고요? 하셔도 됩니다만, 이러면 일단 타 동아리에게도 알려줘야할 거 같고, 프로젝트명도 좀 바꿔야할 거 같습니다.

**Comment by miaekim** [comment]
you don't have to rush, I meant `future works`. :)

**Comment by benjioh5** [comment]
ok, i see
